### ISSUE TITLE
车位的靠后中心点的选取有什么原则吗？

### ISSUE THREAD

**Issue by Just-w22** [MiyagiRonin/auto_parking#2]
show_animation.py这个显示动画轨迹，车位靠后的中心点是怎么选取的呢？我写了一份平行泊车的代码，想要 根博主的垂直代码 输入输出、原点的坐标选取车位靠后的中心点，保持一致，最后合到一起

**Comment by MiyagiRonin** [comment]
C++代码中泊车的目标位姿默认为为0，0，0.5pi且不可更改，python可视化代码中轨迹为车辆后轴中心点，根据车辆参数(vehicle_conf.h和python代码中都写了，需要保持一致)画出车的轮廓。

**Comment by Just-w22** [comment]
博主，您好，我向请教的是 目标位姿（0,0）在车位中的位置 是怎样的？因为车位的坐标点 是以该目标位姿为原点时确定的

**Comment by MiyagiRonin** [comment]
当车泊入时，车的几何中心和车位的几何中心重合即可。略有偏差也没问题，只要距离车位边界的距离足够即可。
